---
- name: Print devicetype
  debug:
    msg: "Device type: {{ devicetype }}"
  #no_log: true

# This checks the ansible_network_os variable. if connection: httpapi is defined in playbook
# this will get problematic cause the ansible_network_os will be cached for all hosts
# => all hosts will use the same ansible_network_os variable => generates error on hosts with another ansible_network_os
# => Error: ... ConnectionError: Method not found ...
- name: Check ansible_network_os
  debug:
    var: ansible_network_os
  #no_log: true

# tasks file for ansible_role_firewallpolicy
- name: implement firewallpolicies
  include_tasks: firewallpolicy.yml
  vars:
    rule_device: "{{ item_policy.device.split('%') | first }}"
    subtask: "{{ devicetype }}_policy.yml"
  loop: "{{ firewallpolicies }}"
  loop_control:
    loop_var: item_policy
  no_log: true



