---
# tasks file for ansible_role_firewallpolicy
- name: implement firewallpolicies
  with_items:
    - "{{ firewallpolicies }}"
  include_tasks: firewallpolicy.yml
  vars:
    thing: "{{ item_policy }}"