---
- name: Print devicetype
  debug:
    msg: "Device type: {{ devicetype }}"
  #no_log: true

# tasks file for ansible_role_firewallpolicy
- name: implement firewallpolicies
  include_tasks: firewallpolicy.yml
  vars:
    rule_device: "{{ item_policy.device.split('%') | first }}"
    subtask: "{{ devicetype }}_policy.yml"
  loop: "{{ firewallpolicies }}"
  loop_control:
    loop_var: item_policy
  no_log: true



