---
# REQUIRED: pip install urllib3

#- name: Include needed variables
#  include_vars: cisco-fmc_policy.yml

#- name: Schreibe die Variable um, wenn eine Bedingung erfüllt ist
#  set_fact:
#    my_variable: "new_value"
#  when: my_variable == "old_value"

- name: Get Domain
  cisco.fmcansible.fmc_configuration:
    operation: getAllDomain
    register_as: domain

- name: Get Access Policy
  cisco.fmcansible.fmc_configuration:
    operation: getAllAccessPolicy
    path_params:
      domainUUID: '{{ domain[0].uuid }}'
    filters:
      name: '{{ item_policy.polname }}'
    register_as: accesspolicy


- name: Authenticate with Cisco FMC
  uri:
    url: "https://{{ ansible_host }}/api/fmc_platform/v1/auth/generatetoken"
    method: POST
    headers:
      Content-Type: "application/json"
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    force_basic_auth: yes
    status_code: 204
    validate_certs: no
  register: auth_response
  #no_log: true # enable this to hide secrets like the auth-cookie


- name: Get list of devices
  uri:
    url: "https://{{ ansible_host }}/api/fmc_config/v1/domain/{{ domain[0].uuid }}/devices/devicerecords"
    method: GET
    headers:
      X-auth-access-token: "{{ auth_response.set_cookie }}"
      Content-Type: "application/json"
    validate_certs: no
  register: devices_response

- name: Display Device IDs
  debug:
    msg: "{{ devices_response.json.items | json_query('[].{name: name, id: id}') }}"

- name: Fetch route details
  uri:
    url: "https://{{ ansible_host }}/api/fmc_config/v1/domain/{{ domain[0].uuid }}/devices/devicerecords/1/routing"
    method: GET
    headers:
      X-auth-access-token: "{{ auth_response.set_cookie }}"
      Content-Type: "application/json"
    return_content: yes
  register: route_details
- name: Display routes
  debug:
    msg: "{{ route_details.json }}"


- name: Create an access rule allowing trafic from Cisco DevNet
  cisco.fmcansible.fmc_configuration:
    operation: upsertAccessRule
    data:
      name: AllowCiscoTraffic8
      type: accessrule
      action: ALLOW # ALLOW | TRUST | BLOCK | MONITOR | BLOCK_RESET | BLOCK_INTERACTIVE | BLOCK_RESET_INTERACTIVE
      #sendEventsToFMC : true
      commentHistoryList : 
        - date: 0
          comment: "unkown comment"
    path_params:
      containerUUID: '{{ accesspolicy[0].id }}'
      domainUUID: '{{ domain[0].uuid }}'


#"newComments": [
#    "comment1",
#    "comment2"
#  ]

#{
#  "action": "ALLOW",
#  "enabled": true,
#  "type": "AccessRule",
#  "name": "Rule1",
#  "sendEventsToFMC": false,
#  "logFiles": false,
#  "logBegin": false,
#  "logEnd": false,
#  "variableSet": {
#    "name": "Default Set",
#    "id": "VariableSetUUID",
#    "type": "VariableSet"
#  },
#  "vlanTags": {
#    "objects": [
#      {
#        "type": "VlanTag",
#        "name": "vlan_tag_1",
#        "id": "VlanTagUUID1"
#      },
#      {
#        "type": "VlanTag",
#        "name": "vlan_tag_2",
#        "id": "VlanTagUUID2"
#      }
#    ]
#  },
#  "urls": {
#    "urlCategoriesWithReputation": [
#      {
#        "type": "UrlCategoryAndReputation",
#        "category": {
#          "name": "Weapons",
#          "id": "URLCategoryUUID",
#          "type": "URLCategory"
#        },
#        "reputation": "BENIGN_SITES_WITH_SECURITY_RISKS"
#      }
#    ]
#  },
#  "sourceZones": {
#    "objects": [
#      {
#        "name": "External",
#        "id": "SecurityZoneUUID",
#        "type": "SecurityZone"
#      }
#    ]
#  },
#  "destinationZones": {
#    "objects": [
#      {
#        "name": "Internal",
#        "id": "SecurityZoneUUID",
#        "type": "SecurityZone"
#      }
#    ]
#  },
#  "sourcePorts": {
#    "objects": [
#      {
#        "type": "ProtocolPortObject",
#        "name": "AOL",
#        "id": "ProtocolPortObjectUUID"
#      }
#    ]
#  },
#  "sourceDynamicObjects": {
#    "objects": [
#      {
#        "name": "SourceDynamicObject",
#        "id": "dynamicObjectUUID",
#        "type": "DynamicObject"
#      }
#    ]
#  },
#  "destinationDynamicObjects": {
#    "objects": [
#      {
#        "name": "destinationDynamicObject",
#        "id": "dynamicObjectUUID",
#        "type": "DynamicObject"
#      }
#    ]
#  },
#  "destinationPorts": {
#    "objects": [
#      {
#        "type": "ProtocolPortObject",
#        "name": "Bittorrent",
#        "id": "ProtocolPortObjectUUID"
#      }
#    ]
#  },
#  "ipsPolicy": {
#    "type": "IntrusionPolicy",
#    "id": "ipsPolicyUuid",
#    "name": "ipsPlicyName"
#  },
#  "filePolicy": {
#    "type": "FilePolicy",
#    "id": "filePolicyUuid",
#    "name": "filePolicyName"
#  },
#  "snmpConfig": {
#    "id": "snmpConfigUuid",
#    "name": "snmp_alert1",
#    "type": "SNMPAlert"
#  },
#  "syslogConfig": {
#    "id": "syslogConfigUuid",
#    "name": "syslog_alert1",
#    "type": "SyslogAlert"
#  },
#  "newComments": [
#    "comment1",
#    "comment2"
#  ]
#}